title: CISOadvisor.us
description: At CISOadvisor.us, we provide invaluable guidance for businesses navigating the complexities of cybersecurity risk management and digital transformation.
url: https://cisoadvisor.us
baseurl: ""
author:
  name: Christophe Foulon
  email: info@cisoadvisor.us
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
markdown: kramdown
permalink: pretty
include:
  - _includes/head-custom.html
social:
  twitter: your_twitter_handle
  linkedin: your_linkedin_profile
  github: your_github_profile
  facebook: your_facebook_profile
  instagram: your_instagram_profile