title: CISOadvisor.us
description: At CISOadvisor.us, we provide invaluable guidance for businesses navigating the complexities of cybersecurity risk management and digital transformation.
url: https://cisoadvisor.us
baseurl: ""
author:
  name: Christophe Foulon
  email: info@cisoadvisor.us
theme: minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: pretty
social:
  twitter: your_twitter_handle
  linkedin: your_linkedin_profile
  github: your_github_profile
  facebook: your_facebook_profile
  instagram: your_instagram_profile